// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupExperimentPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.startupRolloutPrefs.browser.newtabpage.activity-stream.asrouter.providers.snippets", "{\"id\":\"snippets\",\"enabled\":true,\"type\":\"remote\",\"url\":\"https://snippets.cdn.mozilla.net/%STARTPAGE_VERSION%/%NAME%/%VERSION%/%APPBUILDID%/%BUILD_TARGET%/%LOCALE%/%CHANNEL%/%OS_VERSION%/%DISTRIBUTION%/%DISTRIBUTION_VERSION%/\",\"updateCycleInMs\":14400000}");
user_pref("app.normandy.startupRolloutPrefs.browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts", true);
user_pref("app.normandy.user_id", "395a17e7-a26c-4088-919a-ded808e9f71e");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1553680637);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1553680757);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1553557477);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1553557717);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1553557597);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1553557814);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1553680997);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1553680877);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 675840);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.migration.version", 76);
user_pref("browser.newtabpage.activity-stream.impressionId", "{11291b8e-163d-4a17-b288-91b08b91e82c}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1553641200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1553680616904");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1553682440904");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1553680617529");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1553684217529");
user_pref("browser.search.hiddenOneOffs", "Yahoo,Ixquick");
user_pref("browser.search.region", "FR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181209160329");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1553681013");
user_pref("browser.startup.homepage", "www.duckduckgo.com");
user_pref("browser.startup.homepage_override.buildID", "20181209160329");
user_pref("browser.startup.homepage_override.mstone", "64.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"privatebrowsing-button\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":15,\"newElementCount\":3}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "64.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("dom.push.userAgentID", "bafa425895954b6685385e4f49763aab");
user_pref("extensions.blocklist.lastModified", "Tue, 26 Mar 2019 17:13:55 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1553680639);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181209160329");
user_pref("extensions.lastAppVersion", "64.0");
user_pref("extensions.lastPlatformVersion", "64.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{95d10150-ae50-44cb-8824-c8dcc282536f}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"e6908f06-e945-4ed6-a821-3c4c371119a0\",\"screenshots@mozilla.org\":\"bff2b212-65a1-4d81-b4bb-df153fba1086\",\"webcompat-reporter@mozilla.org\":\"fc214b28-8bcc-46e7-82e4-088c8ec06fbf\",\"webcompat@mozilla.org\":\"5680a80d-3620-442c-8ac3-0126c9ddb570\",\"fxmonitor@mozilla.org\":\"1827bdfc-0b38-4383-9ab0-69f62f277c40\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1553557479);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181209160329");
user_pref("media.gmp-manager.lastCheck", 1553680639);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "16569150-74e4-47a7-9fd9-987446304294");
user_pref("security.sandbox.plugin.tempDirSuffix", "34d38f32-999f-40d9-bb6d-2666a1d2e0f7");
user_pref("services.blocklist.addons.checked", 1553680610);
user_pref("services.blocklist.gfx.checked", 1553680610);
user_pref("services.blocklist.onecrl.checked", 1553680610);
user_pref("services.blocklist.pinning.checked", 1553680610);
user_pref("services.blocklist.plugins.checked", 1553680610);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_update_seconds", 1553680610);
user_pref("services.settings.main.language-dictionaries.last_check", 1553680610);
user_pref("services.settings.main.onboarding.last_check", 1553680610);
user_pref("services.settings.main.sites-classification.last_check", 1553680610);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1553681010);
user_pref("toolkit.telemetry.cachedClientID", "f2bbc0dd-4fea-4649-b741-9af9728820a8");
user_pref("toolkit.telemetry.previousBuildID", "20181209160329");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
